### ISSUE TITLE
error with ipaddr_whois

### ISSUE THREAD

**Issue by potentiallyunwanted** [digitalshadows/shadowline-api#2]
When I run the following command: 
`shadowline --profile test ipaddr_whois -i 103.111.22.2`
I get the following error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/shadowline", line 11, in <module>
    load_entry_point('shadowline==0.0.1', 'console_scripts', 'shadowline')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shadowline/shadowline.py", line 253, in ipaddr_whois
    sl_console.echo_ipaddr_whois(json_data, ipaddr)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shadowline/sl_console.py", line 65, in echo_ipaddr_whois
    print(blessed_t.move_right, blessed_t.move_right, blessed_t.yellow("NetName"), blessed_t.cyan(json_data['netName']), blessed_t.yellow("Country"), blessed_t.cyan(json_data['countryName']), blessed_t.yellow("IP range start"), blessed_t.cyan(json_data['ipRangeStart']), blessed_t.yellow("IP range end"), blessed_t.cyan(json_data['ipRangeEnd']))
KeyError: 'countryName'

```
This doesn't happen with every IP. 

Thanks for the help.

**Comment by adjectiveanimal** [comment]
Thanks for the bug report, we'll look into this and let you know.

**Comment by adjectiveanimal** [comment]
I have fixed the issue and pushed a new version of Shadowline to master. Please update with "git pull", and re-install Shadowline and let us know if you have any more problems. Thanks again!
